#!/usr/bin/env python3
"""
Modal App: onboard_new_client
Auto-generated by deploy_to_modal.py

Description: This workflow automates the client onboarding process from contract signing through kickoff call, ensuring consistent, professional onboarding every time.

Deploy: modal deploy execution/modal_apps/onboard_new_client_modal.py
Logs:   modal logs onboard_new_client
"""

import modal
import os
import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime

app = modal.App("onboard_new_client")

# Build image with required packages - v3 with apify-client
image = (
    modal.Image.debian_slim(python_version="3.11")
    .run_commands("echo 'build-v4-onboarding-post-kickoff'")
    .pip_install("anthropic", "python-dotenv", "requests", "fastapi", "pandas", "apify-client", "google-auth", "google-auth-oauthlib", "google-api-python-client", "gspread")
    .add_local_dir("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/execution", remote_path="/app/execution")
    .add_local_dir("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/directives", remote_path="/app/directives")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/.env", remote_path="/app/.env")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/token_docs.json", remote_path="/app/token.json")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/token_gmail.json", remote_path="/app/token_gmail.json")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/credentials.json", remote_path="/app/credentials.json")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_hormozi_sales_training.md", remote_path="/app/skills/SKILL_BIBLE_hormozi_sales_training.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_hormozi_customer_retention.md", remote_path="/app/skills/SKILL_BIBLE_hormozi_customer_retention.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_agency_sales_system.md", remote_path="/app/skills/SKILL_BIBLE_agency_sales_system.md"))

secrets = [
    modal.Secret.from_name("slack-webhook")
]


def slack_notify(message: str):
    """Send notification to Slack if configured."""
    import requests
    webhook_url = os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        return
    try:
        requests.post(webhook_url, json={"text": message}, timeout=5)
    except Exception:
        pass


def run_script(script_name: str, args: list = None) -> dict:
    """Run an execution script and return output."""
    script_path = f"/app/execution/{script_name}.py"
    if not Path(script_path).exists():
        return {"error": f"Script not found: {script_name}"}
    
    cmd = ["python3", script_path] + (args or [])
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=600,
            cwd="/app",
            env={**os.environ, "PYTHONPATH": "/app"}
        )
        return {
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode,
            "success": result.returncode == 0
        }
    except subprocess.TimeoutExpired:
        return {"error": "Script timed out after 10 minutes"}
    except Exception as e:
        return {"error": str(e)}


@app.function(image=image, secrets=secrets, timeout=900)
@modal.fastapi_endpoint(method="POST")
def webhook(payload: dict = None):
    """
    Webhook endpoint for onboard_new_client
    
    POST /webhook
    Body: {"data": {...}}
    """
    payload = payload or {}
    input_data = payload.get("data", payload)
    
    slack_notify(f"🚀 *{'onboard_new_client'}* triggered\n```{json.dumps(input_data, indent=2)[:500]}```")
    
    try:
        # Build command args from input data
        args = []
        for key, value in input_data.items():
            if value is not None and value != "":
                # Convert underscores to hyphens for CLI args
                arg_key = key.replace("_", "-")
                args.extend([f"--{arg_key}", str(value)])
        
        # Run the main execution script
        result = run_script("onboarding_post_kickoff", args)
        
        if result.get("success"):
            slack_notify(f"✅ *{'onboard_new_client'}* completed successfully")
        else:
            slack_notify(f"❌ *{'onboard_new_client'}* failed:\n```{result.get('stderr', result.get('error', 'Unknown error'))[:500]}```")
        
        return {
            "status": "success" if result.get("success") else "error",
            "directive": "onboard_new_client",
            "result": result,
            "timestamp": datetime.utcnow().isoformat()
        }
        
    except Exception as e:
        slack_notify(f"💥 *{'onboard_new_client'}* error: {str(e)}")
        return {"status": "error", "error": str(e)}


@app.function(image=image, secrets=secrets, timeout=30)
@modal.fastapi_endpoint(method="GET")
def health():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "app": "onboard_new_client",
        "timestamp": datetime.utcnow().isoformat()
    }


@app.function(image=image, secrets=secrets, timeout=30)
@modal.fastapi_endpoint(method="GET")
def info():
    """Get info about this workflow."""
    return {
        "name": "onboard_new_client",
        "description": "This workflow automates the client onboarding process from contract signing through kickoff call, ensuring consistent, professional onboarding every time.",
        "integrations": ['slack', 'google_sheets', 'gmail'],
        "scripts": ['welcome_client_emails', 'update_sheet', 'onboarding_post_kickoff'],
        "inputs": {'Client Name': {'type': 'Full', 'required': False}, 'Client Email': {'type': 'Email', 'required': False}, 'Company Name': {'type': 'Client', 'required': False}, 'Service Type': {'type': 'What', 'required': False}, 'Deal Value': {'type': 'Monthly', 'required': False}, 'Start Date': {'type': 'When', 'required': False}, 'Account Manager': {'type': 'Who', 'required': False}}
    }
