#!/usr/bin/env python3
"""
Modal App: stripe_client_onboarding
Auto-generated by deploy_to_modal.py
Build: 20260107_164755

Description: Automated client onboarding triggered by Stripe subscription payment. Creates Slack channel, sends branded HTML welcome email, researches the client via Perplexity, searches Fathom for past conversati

Deploy: modal deploy execution/modal_apps/stripe_client_onboarding_modal.py
Logs:   modal logs stripe_client_onboarding
"""

import modal
import os
import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime

app = modal.App("stripe_client_onboarding")

# Build image with required packages (Build: 20260107_164755)
image = (
    modal.Image.debian_slim(python_version="3.11")
    .run_commands("echo 'Build: 20260107_164755'")
    .pip_install("anthropic", "python-dotenv", "requests", "fastapi", "pandas", "apify-client", "slack-sdk", "openai", "google-auth", "google-auth-oauthlib", "google-api-python-client", "gspread")
    .add_local_dir("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/execution", remote_path="/app/execution")
    .add_local_dir("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/directives", remote_path="/app/directives")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/.env", remote_path="/app/.env")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/token_docs.json", remote_path="/app/token_docs.json")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/token_docs.json", remote_path="/app/token.json")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/token_gmail.json", remote_path="/app/token_gmail.json")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/credentials.json", remote_path="/app/credentials.json")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/token.pickle", remote_path="/app/token.pickle")
)

secrets = [
    modal.Secret.from_name("openrouter-secret"),
    modal.Secret.from_name("slack-webhook")
]


def slack_notify(message: str):
    """Send notification to Slack if configured."""
    import requests
    webhook_url = os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        return
    try:
        requests.post(webhook_url, json={"text": message}, timeout=5)
    except Exception:
        pass


def run_script(script_name: str, args: list = None) -> dict:
    """Run an execution script and return output."""
    script_path = f"/app/execution/{script_name}.py"
    if not Path(script_path).exists():
        return {"error": f"Script not found: {script_name}"}
    
    cmd = ["python3", script_path] + (args or [])
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=600,
            cwd="/app",
            env={**os.environ, "PYTHONPATH": "/app"}
        )
        return {
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode,
            "success": result.returncode == 0
        }
    except subprocess.TimeoutExpired:
        return {"error": "Script timed out after 10 minutes"}
    except Exception as e:
        return {"error": str(e)}


@app.function(image=image, secrets=secrets, timeout=900)
@modal.fastapi_endpoint(method="POST")
def webhook(payload: dict = None):
    """
    Webhook endpoint for stripe_client_onboarding
    
    POST /webhook
    Body: {"data": {...}}
    """
    payload = payload or {}
    input_data = payload.get("data", payload)
    
    slack_notify(f"🚀 *{'stripe_client_onboarding'}* triggered\n```{json.dumps(input_data, indent=2)[:500]}```")
    
    try:
        # Build command args from input data
        args = []
        for key, value in input_data.items():
            if value is not None and value != "":
                # Keep original key format (scripts may use underscores or hyphens)
                args.extend([f"--{key}", str(value)])
        
        # Run the main execution script
        result = run_script("stripe_client_onboarding", args)
        
        if result.get("success"):
            slack_notify(f"✅ *{'stripe_client_onboarding'}* completed successfully")
        else:
            slack_notify(f"❌ *{'stripe_client_onboarding'}* failed:\n```{result.get('stderr', result.get('error', 'Unknown error'))[:500]}```")
        
        return {
            "status": "success" if result.get("success") else "error",
            "directive": "stripe_client_onboarding",
            "result": result,
            "timestamp": datetime.utcnow().isoformat()
        }
        
    except Exception as e:
        slack_notify(f"💥 *{'stripe_client_onboarding'}* error: {str(e)}")
        return {"status": "error", "error": str(e)}


@app.function(image=image, secrets=secrets, timeout=30)
@modal.fastapi_endpoint(method="GET")
def health():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "app": "stripe_client_onboarding",
        "timestamp": datetime.utcnow().isoformat()
    }


@app.function(image=image, secrets=secrets, timeout=30)
@modal.fastapi_endpoint(method="GET")
def info():
    """Get info about this workflow."""
    return {
        "name": "stripe_client_onboarding",
        "description": "Automated client onboarding triggered by Stripe subscription payment. Creates Slack channel, sends branded HTML welcome email, researches the client via Perplexity, searches Fathom for past conversati",
        "integrations": ['slack', 'google_docs', 'gmail', 'openrouter', 'openai'],
        "scripts": ['stripe_client_onboarding'],
        "inputs": {}
    }
