#!/usr/bin/env python3
"""
Modal App: vsl_funnel_writer
Auto-generated by deploy_to_modal.py

Description: This workflow generates complete VSL (Video Sales Letter) funnel copy including script, landing page, and email sequence using proven frameworks.

Deploy: modal deploy execution/modal_apps/vsl_funnel_writer_modal.py
Logs:   modal logs vsl_funnel_writer
"""

import modal
import os
import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime

app = modal.App("vsl_funnel_writer")

# Build image with required packages
image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install("anthropic", "python-dotenv", "requests", "fastapi", "google-auth", "google-auth-oauthlib", "google-api-python-client", "gspread", "openai")
    .add_local_dir("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/execution", remote_path="/app/execution")
    .add_local_dir("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/directives", remote_path="/app/directives")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/.env", remote_path="/app/.env")
)

secrets = [
    modal.Secret.from_name("openrouter-secret")
]


def slack_notify(message: str):
    """Send notification to Slack if configured."""
    import requests
    webhook_url = os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        return
    try:
        requests.post(webhook_url, json={"text": message}, timeout=5)
    except Exception:
        pass


def run_script(script_name: str, args: list = None) -> dict:
    """Run an execution script and return output."""
    script_path = f"/app/execution/{script_name}.py"
    if not Path(script_path).exists():
        return {"error": f"Script not found: {script_name}"}
    
    cmd = ["python3", script_path] + (args or [])
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=600,
            cwd="/app",
            env={**os.environ, "PYTHONPATH": "/app"}
        )
        return {
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode,
            "success": result.returncode == 0
        }
    except subprocess.TimeoutExpired:
        return {"error": "Script timed out after 10 minutes"}
    except Exception as e:
        return {"error": str(e)}


@app.function(image=image, secrets=secrets, timeout=900)
@modal.fastapi_endpoint(method="POST")
def webhook(payload: dict = None):
    """
    Webhook endpoint for vsl_funnel_writer
    
    POST /webhook
    Body: {"data": {...}}
    """
    payload = payload or {}
    input_data = payload.get("data", payload)
    
    slack_notify(f"🚀 *{'vsl_funnel_writer'}* triggered\n```{json.dumps(input_data, indent=2)[:500]}```")
    
    try:
        # Build command args from input data
        args = []
        for key, value in input_data.items():
            if value is not None and value != "":
                args.extend([f"--{key}", str(value)])
        
        # Run the main execution script
        result = run_script("generate_vsl_funnel", args)
        
        if result.get("success"):
            slack_notify(f"✅ *{'vsl_funnel_writer'}* completed successfully")
        else:
            slack_notify(f"❌ *{'vsl_funnel_writer'}* failed:\n```{result.get('stderr', result.get('error', 'Unknown error'))[:500]}```")
        
        return {
            "status": "success" if result.get("success") else "error",
            "directive": "vsl_funnel_writer",
            "result": result,
            "timestamp": datetime.utcnow().isoformat()
        }
        
    except Exception as e:
        slack_notify(f"💥 *{'vsl_funnel_writer'}* error: {str(e)}")
        return {"status": "error", "error": str(e)}


@app.function(image=image, secrets=secrets, timeout=30)
@modal.fastapi_endpoint(method="GET")
def health():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "app": "vsl_funnel_writer",
        "timestamp": datetime.utcnow().isoformat()
    }


@app.function(image=image, secrets=secrets, timeout=30)
@modal.fastapi_endpoint(method="GET")
def info():
    """Get info about this workflow."""
    return {
        "name": "vsl_funnel_writer",
        "description": "This workflow generates complete VSL (Video Sales Letter) funnel copy including script, landing page, and email sequence using proven frameworks.",
        "integrations": ['slack', 'google_docs', 'gmail', 'openrouter', 'openai'],
        "scripts": ['generate_vsl_funnel'],
        "inputs": {'Client Name': {'type': 'text', 'required': True}, 'Product/Service Name': {'type': 'text', 'required': True}, 'Price Point': {'type': 'text', 'required': True}, 'Payment Options': {'type': 'text', 'required': False}, 'Target Audience': {'type': 'textarea', 'required': True}, 'Main Pain Points': {'type': 'textarea', 'required': True}, 'Unique Mechanism': {'type': 'textarea', 'required': True}, 'Transformation Promise': {'type': 'textarea', 'required': True}, 'Client Results': {'type': 'textarea', 'required': True}, 'Core Offer Details': {'type': 'textarea', 'required': True}, 'Bonus Stack': {'type': 'textarea', 'required': True}, 'Total Value': {'type': 'text', 'required': True}, 'VSL Style': {'type': 'dropdown', 'required': True}, 'VSL Length': {'type': 'dropdown', 'required': True}, 'Urgency Element': {'type': 'text', 'required': True}, 'Guarantee': {'type': 'text', 'required': True}}
    }
