#!/usr/bin/env python3
"""
Modal App: vsl_funnel_orchestrator
Auto-generated by deploy_to_modal.py

Description: **Master orchestrator** that coordinates the complete VSL funnel creation pipeline. Single entry point that triggers all sub-workflows in sequence, manages data flow, handles errors, and delivers fina

Deploy: modal deploy execution/modal_apps/vsl_funnel_orchestrator_modal.py
Logs:   modal logs vsl_funnel_orchestrator
"""

import modal
import os
import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime

app = modal.App("vsl_funnel_orchestrator")

# Build image with required packages
image = (
    modal.Image.debian_slim(python_version="3.11")
    .pip_install("anthropic", "python-dotenv", "requests", "fastapi", "google-auth", "google-auth-oauthlib", "google-api-python-client", "gspread", "openai")
    .add_local_dir("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/execution", remote_path="/app/execution")
    .add_local_dir("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/directives", remote_path="/app/directives")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/.env", remote_path="/app/.env")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_vsl_writing_production.md", remote_path="/app/skills/SKILL_BIBLE_vsl_writing_production.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_email_campaign_copy_design.md", remote_path="/app/skills/SKILL_BIBLE_email_campaign_copy_design.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_hormozi_10x_pricing.md", remote_path="/app/skills/SKILL_BIBLE_hormozi_10x_pricing.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_hormozi_email_marketing_complete.md", remote_path="/app/skills/SKILL_BIBLE_hormozi_email_marketing_complete.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_hormozi_sales_training.md", remote_path="/app/skills/SKILL_BIBLE_hormozi_sales_training.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_hormozi_marketing_mastery.md", remote_path="/app/skills/SKILL_BIBLE_hormozi_marketing_mastery.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_funnel_copywriting_mastery.md", remote_path="/app/skills/SKILL_BIBLE_funnel_copywriting_mastery.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_cold_email_mastery.md", remote_path="/app/skills/SKILL_BIBLE_cold_email_mastery.md")
    .add_local_file("/Users/lucasnolan/Documents/Work/Client Ascension/AI Development/Agentic Workflows/skills/SKILL_BIBLE_vsl_script_mastery_fazio.md", remote_path="/app/skills/SKILL_BIBLE_vsl_script_mastery_fazio.md"))

secrets = [
    modal.Secret.from_name("openrouter-secret")
]


def slack_notify(message: str):
    """Send notification to Slack if configured."""
    import requests
    webhook_url = os.getenv("SLACK_WEBHOOK_URL")
    if not webhook_url:
        return
    try:
        requests.post(webhook_url, json={"text": message}, timeout=5)
    except Exception:
        pass


def run_script(script_name: str, args: list = None) -> dict:
    """Run an execution script and return output."""
    script_path = f"/app/execution/{script_name}.py"
    if not Path(script_path).exists():
        return {"error": f"Script not found: {script_name}"}
    
    cmd = ["python3", script_path] + (args or [])
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=600,
            cwd="/app",
            env={**os.environ, "PYTHONPATH": "/app"}
        )
        return {
            "stdout": result.stdout,
            "stderr": result.stderr,
            "returncode": result.returncode,
            "success": result.returncode == 0
        }
    except subprocess.TimeoutExpired:
        return {"error": "Script timed out after 10 minutes"}
    except Exception as e:
        return {"error": str(e)}


@app.function(image=image, secrets=secrets, timeout=900)
@modal.fastapi_endpoint(method="POST")
def webhook(payload: dict = None):
    """
    Webhook endpoint for vsl_funnel_orchestrator
    
    POST /webhook
    Body: {"data": {...}}
    """
    payload = payload or {}
    input_data = payload.get("data", payload)
    
    slack_notify(f"🚀 *{'vsl_funnel_orchestrator'}* triggered\n```{json.dumps(input_data, indent=2)[:500]}```")
    
    try:
        # Build command args from input data
        args = []
        for key, value in input_data.items():
            if value is not None and value != "":
                args.extend([f"--{key}", str(value)])
        
        # Run the main execution script
        result = run_script("generate_complete_vsl_funnel", args)
        
        if result.get("success"):
            slack_notify(f"✅ *{'vsl_funnel_orchestrator'}* completed successfully")
        else:
            slack_notify(f"❌ *{'vsl_funnel_orchestrator'}* failed:\n```{result.get('stderr', result.get('error', 'Unknown error'))[:500]}```")
        
        return {
            "status": "success" if result.get("success") else "error",
            "directive": "vsl_funnel_orchestrator",
            "result": result,
            "timestamp": datetime.utcnow().isoformat()
        }
        
    except Exception as e:
        slack_notify(f"💥 *{'vsl_funnel_orchestrator'}* error: {str(e)}")
        return {"status": "error", "error": str(e)}


@app.function(image=image, secrets=secrets, timeout=30)
@modal.fastapi_endpoint(method="GET")
def health():
    """Health check endpoint."""
    return {
        "status": "healthy",
        "app": "vsl_funnel_orchestrator",
        "timestamp": datetime.utcnow().isoformat()
    }


@app.function(image=image, secrets=secrets, timeout=30)
@modal.fastapi_endpoint(method="GET")
def info():
    """Get info about this workflow."""
    return {
        "name": "vsl_funnel_orchestrator",
        "description": "**Master orchestrator** that coordinates the complete VSL funnel creation pipeline. Single entry point that triggers all sub-workflows in sequence, manages data flow, handles errors, and delivers fina",
        "integrations": ['slack', 'google_docs', 'gmail', 'openrouter', 'anthropic', 'openai'],
        "scripts": ['generate_complete_vsl_funnel', 'test_trigger_task'],
        "inputs": {}
    }
